name: Build and test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
        directory: [common, frcal, jcal]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci --include=dev
      - name: Build
        run: |
          cd ${{ matrix.directory }}
          [ "${{ matrix.directory }}" != common ] && CI=false npm run build
          npm test -- --watchAll=false --ci --passWithNoTests
